//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Auction_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidOffer
    {

        public BidOffer()
        {

        }

        public BidOffer(BidOffer bo)
        {
            this.Username = bo.User.Username;
            this.OfferedPrice = bo.OfferedPrice;
        }

        public BidOffer(int UserID,int ProductID,decimal OfferedPrice)
        {
            this.UserID = UserID;
            this.ProductID = ProductID;
            this.OfferedPrice = OfferedPrice;
        }
        public String Username { set; get; }
        public int BidOfferID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public decimal OfferedPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
