//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Auction_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BidOffers = new HashSet<BidOffer>();
        }

        public Product(Product product,List<BidOffer> bidOffers)
        {
            this.ProductID = product.ProductID;
            this.UserID = product.UserID;
            this.ProductName = product.ProductName;
            this.InitialPrice = product.InitialPrice;
            this.IsSold = product.IsSold;

            BidOffers = new List<BidOffer>();
            foreach(BidOffer bo in bidOffers)
            {
                BidOffers.Add(new BidOffer(bo));
            }
        }

        public Product(int UserID,String ProductName,decimal InitialPrice,bool IsSold)
        {
            this.UserID = UserID;
            this.ProductName = ProductName;
            this.InitialPrice = InitialPrice;
            this.IsSold = IsSold;      
        }

        public Product(Product product, decimal MaxBid)
        {
            this.ProductID = product.ProductID;
            this.Username = product.User.Username;
            this.UserID = product.UserID;
            this.ProductName = product.ProductName;
            this.InitialPrice = product.InitialPrice;
            this.IsSold = product.IsSold;
            this.MaxBid = MaxBid;
        }

        public Product(Product product)
        {
            this.ProductID = product.ProductID;
            this.UserID = product.UserID;
            this.Username = product.User.Username;
            this.ProductName = product.ProductName;
            this.InitialPrice = product.InitialPrice;
            this.IsSold = product.IsSold;
        }
        public String Username { set; get; }
        public decimal MaxBid { get; set; }
    
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public string ProductName { get; set; }
        public decimal InitialPrice { get; set; }
        public bool IsSold { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidOffer> BidOffers { get; set; }
        public virtual User User { get; set; }
    }
}
