//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Auction_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.BidOffers = new HashSet<BidOffer>();
            this.Products = new HashSet<Product>();
        }

        public User(String Username,String Password,String Login,long Tel)
        {
            this.Username = Username;
            this.Password = Password;
            this.Login = Login;
            this.Tel = Tel;
        }

        public User(User user)
        {
            this.UserID = user.UserID;
            this.Username = user.Username;
            this.Password = user.Password;
            this.Login = user.Login;
            this.Tel = user.Tel;
        }

        public int UserID { get; set; }
        public string Username { get; set; }
        public long Tel { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BidOffer> BidOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
